services:
  websters:
    container_name: websters
    build:
      context: .
      target: production
    restart: always
    ports:
      - "42069:80"
      #- "443:443" # HTTPS
      #- "443:443/udp" # HTTP/3
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: webstersdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  caddy_data:
  caddy_config:
  mysql_data:
